<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitced06565e76f77e9d748fe658a260a11
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dejurin\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dejurin\\' => 
        array (
            0 => __DIR__ . '/..' . '/dejurin/php-google-translate-for-free/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitced06565e76f77e9d748fe658a260a11::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitced06565e76f77e9d748fe658a260a11::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitced06565e76f77e9d748fe658a260a11::$classMap;

        }, null, ClassLoader::class);
    }
}
