<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2a423ac13686b26fd6aa330ca30560b9
{
    public static $prefixLengthsPsr4 = array (
        'v' => 
        array (
            'voku\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'voku\\' => 
        array (
            0 => __DIR__ . '/..' . '/voku/stop-words/src/voku',
            1 => __DIR__ . '/..' . '/voku/portable-ascii/src/voku',
        ),
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'URLify' => 
            array (
                0 => __DIR__ . '/..' . '/jbroadway/urlify',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2a423ac13686b26fd6aa330ca30560b9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2a423ac13686b26fd6aa330ca30560b9::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit2a423ac13686b26fd6aa330ca30560b9::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit2a423ac13686b26fd6aa330ca30560b9::$classMap;

        }, null, ClassLoader::class);
    }
}
